name: flutter_testing_methods
description: A flutter project illustrates testing methods.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.0.1
  # HTTP Client
  dio: ^4.0.6

dev_dependencies:
  mocktail: ^0.3.0

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true